### ISSUE TITLE
do you accept donations?

### ISSUE THREAD

**Issue by benvvalk** [rickbutton/workspacer#132]
Thanks so much for making this and for sharing it publicly, @rickbutton!

Do you accept donations for this project?

I'm so happy this exists, and it works a lot better than I would have expected! I've always wanted a tiling window manager for Windows and I've even tried to create one myself a couple of times (half-assedly).

**Comment by josteink** [comment]
If you're interested @rickbutton, Github has a [donations-program for developers](https://github.com/sponsors) these days, and it's out of beta.

**Comment by rickbutton** [comment]
Hi @benvvalk . I really appreciate the support! I don't want to accept donations (or sponsors @josteink ) because I wouldn't feel comfortable accepting donations for a project that I don't have much time to work on. `workspacer` is a project born out of need, and I don't have any desire to monetize it. If you still want to donate something, I want to redirect your donation to [National Bail Out](https://secure.actblue.com/donate/freeblackmamas2020) or another deserving organization.

Thank you for using workspacer!
