### ISSUE TITLE
Wrong code in config tab of the website

### ISSUE THREAD

**Issue by GGrassia** [rickbutton/workspacer#134]
Hi!
The code for unsubscribing keybindings on the web page throws an exception.
Statements are:

`context.Keybindings.Unsubscribe(mod, Keys.Y);` and 
`context.Keybindings.UnsubscribeAll();` 

while they should be:

`context.Keybinds.Unsubscribe(mod, Keys.Y);` and 
`context.Keybinds.UnsubscribeAll();`

Hope I've been helpful, and keep up the good work :)

**Comment by josteink** [comment]
This documentation-error is a long-standing bug, and even as the one who implemented/fixed the first operation, I have no idea where the actual documentation is stored/maintained/built.

Something you can look at, @rickbutton ?

**Comment by rickbutton** [comment]
The website is generated from the contents of the `docs` folder in this repo, it uses `hugo` to build it. The production website is deployed automatically on merges into master, because I have an Azure Pipeline setup to auto deploy on merge, so all we need to do is update this file: https://github.com/rickbutton/workspacer/blob/master/docs/content/config.md .

**Comment by josteink** [comment]
Fixed in https://github.com/rickbutton/workspacer/pull/135.
