### ISSUE TITLE
Implementation of GetWindowsRect vs DwmGetWindowAttribute --> Gaps

### ISSUE THREAD

**Issue by N1x0** [rickbutton/workspacer#139]
So while having a look into the idea of gaps I was wondering why by default there are gaps between windows at all. From what I understand this is due to some very weird behaviour of windows 10. Namely `GetWindowsRect` and `DwmGetWindowAttribute` do not report the same positions. This is because windows have a shadow or transparent area that increases the actual window size by 7px. 

So `GetWindowsRect` reports the border of the window **including** the transparent border, while `DwmGetWindowAttribute` shows the *inside* so to speak, without the border. 

One suggestion was to adjust dwm by using `WM_NCCALCSIZE(0,0) ` 

I will try to find a way on how to do this because I think fundamentally this should serve as the basis to implement the concept of gaps but I am sadly not confident at all because of my limited programming skills.

As always thank you @rickbutton for this amazing tool.

Here are the SO posts I found when looking at the issue.
[Windows 10 screen coordinates are offset by 7](https://stackoverflow.com/questions/42473554/windows-10-screen-coordinates-are-offset-by-7/42491227#42491227)
[Resizing windows 10 and ignore transparent border](https://stackoverflow.com/questions/47679911/how-to-resize-a-windows-10-window-and-ignore-the-transparent-border)
[Retrieve Window Size without windows shadows](https://stackoverflow.com/questions/32159675/retrieve-window-size-without-windows-shadows/32645155#32645155)

**Comment by lauverityhill** [comment]
I have been digging through the source for the past few days (though I can't understand about 60% of it, since I'm fairly new to C# and programming in general).

There is only one instance of `GetWindowRect` on the entire solution, it's on `\src\workspacer.Native\Native\WindowsWindow.cs`.

I was able to replace `GetWindowRect` with `DwmGetWindowAttribute`. However, sadly, it only affects the behavior of the highlights that surround `FocusedWindows` (whenever you click on a new workspace).

![image](https://user-images.githubusercontent.com/68158964/99797377-1abc2e00-2b6a-11eb-9816-7dc0523312a3.png)


My guess is that, the various `LayoutEngines` are to blame, or some component of them. `IWindow`, `IWindowLocation`, or `CalcLayout`

**Comment by MSylvia** [comment]
I started working to fix the gap issue here: https://github.com/MSylvia/workspacer/tree/fix-gap-issue

I now have it where all the gaps are basically gone using a combination of `GetWindowRect` and `DwmGetWindowAttribute` to compute an offset to apply to the final window position.

With this change windows that previously had gaps on the Left, Right and Bottom (like Explorer, Firefox, Edge, and Terminal) no longer do. 

![fix](https://user-images.githubusercontent.com/624483/100185739-9394f000-2eb2-11eb-8d69-6f7ce20630d0.PNG)

**Comment by josteink** [comment]
Nice. Feel free to provide a PR for your changes 🙂

**Comment by N1x0** [comment]
Wow absolutely terrific @MSylvia , do you think it's possible to add another offset that's user configurable from within the config file? That way end-users would have full control over gaps similar to `i3-gaps`

**Comment by MSylvia** [comment]
@josteink Sure I can PR it after I clean it up a little and remove my test logging.

@N1x0 Yeah it should be possible to have a user configurable gaps like `i3-gaps`.
I also noticed the 1px gap on the applications that needed the offset. It seems to be more visible when they are not selected. I swear there was a toggle somewhere in the `Settings` app that effected that but it was late and I can't seem to find it now.

**Comment by rickbutton** [comment]
Great work all! Please submit a PR for the gap fixes if you would like, I will gladly review it.

In terms of configurable gap support, absolutely, I see no reason not to include it. I only ask that if it is implemented it be done in a separate PR, so that the fixes can be reviewed independently from the new feature.
