### ISSUE TITLE
Workspacer logo

### ISSUE THREAD

**Issue by BeeryShklar** [rickbutton/workspacer#142]
The current logo is a bit boring so i designed some logos for workspacer.
Which one do you think is the best and should i change some thing?

![logo options](https://user-images.githubusercontent.com/52495055/100104420-d6cd6f80-2e6e-11eb-817a-b13999381adc.png)

The original svg file:

[logo.zip](https://github.com/rickbutton/workspacer/files/5590370/logo.zip)

**Comment by josteink** [comment]
I like the second one best. It subtly highlights the tiling.

**Comment by N1x0** [comment]
Agree with josteink, no. 2 is my favourite. Maybe if there's some consensus on the design (and approval from rick of course 😄) we can play with the colors too?

**Comment by rickbutton** [comment]
wow, these are great!

the original logo was something I whipped up in a few minutes to get rid of the default exe icon, so no love lost.

another +1 for number 2. I'm not sure how artwork licensing works in this respect, since this isn't a commit to the repo itself. Are you interested in opening a PR to update the logos in the app?

**Comment by BeeryShklar** [comment]
Sure, I will open a PR for that.

**Comment by josteink** [comment]
Closed via https://github.com/rickbutton/workspacer/pull/145.
