### ISSUE TITLE
Portable build?

### ISSUE THREAD

**Issue by sitiom** [rickbutton/workspacer#151]
It would be great if portable builds were provided as I would like to use this on a computer without admin privileges or on a USB.

**Comment by josteink** [comment]
There's fundamentally nothing about workspacer which requires "installation" or admin-rights.

Since we're already on .NET Core 3.1, I believe it should be possible just to make a [Single File Application](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file) for this, and it should "just work".

Worst case scenario, just ZIPing up the build output and providing that as an artefact too (instead of providing an installer) would probably be adequate too.

Right now though, I can't fix any of those things, because all the CI/build-magic is done using @rickbutton's personal Azure account using Azure Pipelines.

If we could get the [move to GitHub Actions](https://github.com/rickbutton/workspacer/issues/80) done, it might be easier to fix this as a community-effort.

**Comment by rickbutton** [comment]
Yep, the pipeline already actually creates a portable zip of the build output, but there isn't a dashboard or way to publicly download them. GitHub Actions fixes this.
