### ISSUE TITLE
Change 'Alt+←' and 'Alt+→' to something else

### ISSUE THREAD

**Issue by cbuctok** [rickbutton/workspacer#65]
Hello!
'Alt+←' and 'Alt+→' is quite important to browser navigation, I think we should use something else.
Also
Documentation:
```
context.Keybindings.Unsubscribe(mod, Keys.Right);
context.Keybindings.Unsubscribe(mod, Keys.Left)
```
Documentation (by namespace)
```
context.Keybinds.Unsubscribe(mod, Keys.Right);
context.Keybinds.Unsubscribe(mod, Keys.Left)
```
Doesn't work at all.

**Comment by josteink** [comment]
> 'Alt+←' and 'Alt+→' is quite important to browser navigation, I think we should use something else.

I agree. As someone who uses these key-combos all day long, this is quite jarring.

> Documentation (by namespace) ... Doesn't work at all.

Indeed. `IKeybindManager.Unsubscribe` is only defined for the following signature:

````c#
void Unsubscribe(MouseEvent evt);
````

There's no unsubscribe-equivalent for

````c#
void Subscribe(KeyModifiers mod, Keys key, KeybindHandler handler);
````

So default configuration is kinda troublesome, and it can't be easily fixed with the current implementation.

**Comment by josteink** [comment]
I've submitted a PR which fixes this issue.

@cbuctok : Feel free to test if it works for you.

Please note, I had to update my config script to look like this to make workspacer happy:

````c#
    var mod = KeyModifiers.Alt;                       // declare MOD variable
    context.Keybinds.Unsubscribe(mod, Keys.Right);
    context.Keybinds.Unsubscribe(mod, Keys.Left);     // trailing semi-colon
````
