### ISSUE TITLE
Code-architecture question: What's up with the interfaces?

### ISSUE THREAD

**Issue by josteink** [rickbutton/workspacer#78]
Everywhere in the code I see these pairs: `IConfigContext` followed by `ConfixContext`, `ISomething` and `Something`, `IWhatnot` and `Whatnot`.

Usually this can be a good pattern when you expect have multiple implementations, or want something you can mock/isolate in a test-context to make life simpler.

But in the workspacer codebase I see the interfaces used for neither of these things, so they're mostly really just redundant declarations of whatever the class implements anyway.

Is there a general thing I'm missing here? Is this for the sake of plugins? Or are you just trying to plan for the road ahead, without necessarily knowing where, when and whats that's going be?

Please note: This is not meant as criticism, but an honest question from me to better try understand the current code-base and its design.

**Comment by rickbutton** [comment]
In general, there isn't a specific set of design goals that I am aiming for with `workspacer`, mostly because it was created initially as a tool to serve a very specific need of mine (that you share!, tiling window management on Windows). That being said, I wouldn't mind some more formal thought into this.

Interfaces in general make sense to me for the things accessible from the config file? It doesn't really matter, since we compile the config file each time it changes, so we only need source-level backwards compat (so just no name changes), but it makes sense to me.
